routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Auth::routes(['reset' => false, 'register' => false]);


Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::get('/graficos/graficos-total-emprestimos-mensal', 'GraficosController@graficosEmprestimosTotalMensal')->middleware('auth');
Route::get('/graficos/graficos-total-pagamento-mensais', 'GraficosController@graficosTotalPagamentoMensal')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

	Route::get('config', ['as' => 'config.edit', 'uses' => 'ConfiguracaoController@edit']);
	Route::put('config', ['as' => 'config.update', 'uses' => 'ConfiguracaoController@update']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('clientes', 'ClientesController', ['except' => ['show']]);
});


Route::group(['middleware' => 'auth'], function () {
	Route::resource('fluxoSaida', 'FluxoSaidaController');
	Route::get('gerar-pdf-emp/{id}', ['as' => 'fluxoSaida.pdf', 'uses' => 'FluxoSaidaController@gerarPdf']);
	Route::post('pagar', ['as' => 'fluxoSaida.pagamento', 'uses' => 'FluxoSaidaController@pagamento']);
	Route::post('pagar-total', ['as' => 'fluxoSaida.pagamento.total', 'uses' => 'FluxoSaidaController@pagamentoTotal']);
});

app/Clientes.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Clientes extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'telefone', 'cpf', 'indicacao', 'status',
    ];

    protected $dates = ['vencimento', 'created_at'];

    public function fluxoSaida()
    {
      return $this->hasMany('App\FluxoSaida','id_cliente','id');
    }

}

app/Http/Controllers/ClientesController.php
<?php

namespace App\Http\Controllers;

use App\Clientes;
use App\Http\Requests\ClientesRequest;

class ClientesController extends Controller
{

    public function index(Clientes $model)
    {
        return view('clientes.index', ['clientes' => $model->paginate(15)]);
    }

    /**
     * Novo cliente
     *
     * @return \Illuminate\View\View
     */

    public function create()
    {
        return view('clientes.create');
    }

    /**
     * Salvar clientes
     *
     * @param  \App\Http\Requests\ClientesRequest  $request
     * @return \Illuminate\Http\RedirectResponse
     */

    public function store(ClientesRequest $request)
    {

      $request->validate([
        'name' => 'required',
        'email' => 'required',
        'telefone' => 'required',
        'cpf' => 'required',
        'indicacao' => 'required',
      ]);

      Clientes::create($request->all());

      return redirect()->route('clientes.index')
                ->with('success','Cliente cadastrado com sucesso.');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Clientes  $product
     * @return \Illuminate\Http\RedirectResponse
     */

    public function edit(Clientes $cliente)
    {

      $status_a  = "";
      $status_d = "";

      if($cliente->status == 'A'){
        $status_a = "checked";
      }else{
        $status_d = "checked";
      }

      $status = array(
        'a'  => $status_a,
        'd'  => $status_d
      );

      return view('clientes.edit',compact('cliente','status'));
    }

    /**
     * Update the profile
     *
     * @param  \App\Http\Requests\ClientesRequest  $request
     * @return \Illuminate\Http\RedirectResponse
     */

    public function update(ClientesRequest $request)
    {
      $request->validate([
        'name' => 'required',
        'email' => 'required',
        'telefone' => 'required',
        'cpf' => 'required',
        'indicacao' => 'required',
      ]);

      Clientes::whereId($request->id)->update($request->except(['_method','_token']));

      return redirect()->route('clientes.index')
                ->with('success','Cliente atualizado com sucesso.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Clientes  $clientes
     * @return \Illuminate\Http\RedirectResponse
     */

    public function destroy(Clientes $cliente)
    {
        $cliente->delete();

        return redirect()->route('clientes.index')
                        ->with('success','Cliente deletado com sucesso');
    }
}

resources/views/clientes/create.blade.php
@extends('layouts.app', ['page' => __('Gestão de Clientes'), 'pageSlug' => 'clientes'])

@section('content')
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">{{ __('Novo Cliente') }}</h5>
                </div>
                <form method="POST" action="{{ route('clientes.store') }}" autocomplete="off">
                    <div class="card-body">
                            @csrf
                            @method('POST')

                            <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                <label>{{ __('Nome') }}</label>
                                <input type="text" name="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Nome') }}" value="">
                                @include('alerts.feedback', ['field' => 'name'])
                            </div>

                            <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                <label>{{ __('Email') }}</label>
                                <input type="text" name="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" placeholder="{{ __('E-mail') }}" value="">
                                @include('alerts.feedback', ['field' => 'email'])
                            </div>

                            <div class="form-group{{ $errors->has('telefone') ? ' has-danger' : '' }}">
                                <label>{{ __('Telefone') }}</label>
                                <input type="text" id="telefone" name="telefone" class="form-control{{ $errors->has('telefone') ? ' is-invalid' : '' }}" placeholder="{{ __('Telefone') }}" value="">
                                @include('alerts.feedback', ['field' => 'telefone'])
                            </div>

                            <div class="form-group{{ $errors->has('cpf') ? ' has-danger' : '' }}">
                                <label>{{ __('Cpf') }}</label>
                                <input type="text" id="cpf" name="cpf" class="form-control{{ $errors->has('cpf') ? ' is-invalid' : '' }}" placeholder="{{ __('cpf') }}" value="">
                                @include('alerts.feedback', ['field' => 'cpf'])
                            </div>

                            <div class="form-group{{ $errors->has('indicacao') ? ' has-danger' : '' }}">
                                <label>{{ __('Indicação') }}</label>
                                <input type="text" name="indicacao" class="form-control{{ $errors->has('indicacao') ? ' is-invalid' : '' }}" placeholder="{{ __('indicacao') }}" value="">
                                @include('alerts.feedback', ['field' => 'indicacao'])
                            </div>

                            <div class="form-group{{ $errors->has('status') ? ' has-danger' : '' }}">
                                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                                  <label class="btn btn-light active">
                                    <input type="radio" name="status" id="ativo" value="A" checked> Ativo
                                  </label>
                                  <label class="btn btn-light">
                                    <input type="radio" name="status" id="desativado" value="D"> Desativado
                                  </label>
                                </div>
                            </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-fill btn-primary">{{ __('Salvar') }}</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card card-user">
                <div class="card-body">
                    <p class="card-text">
                        <div class="author">
                            <div class="block block-one"></div>
                            <div class="block block-two"></div>
                            <div class="block block-three"></div>
                            <div class="block block-four"></div>
                            <a href="#">
                                <h4 class="title">Bem vindo ao cadastro de clientes</h4>
                                <h5 class="title">{{ auth()->user()->name }}</h5>
                            </a>
                            <p class="description">
                                {{ __('Teste') }}
                            </p>
                        </div>
                    </p>
                    <div class="card-description">
                        {{ __('Tela destinada ao cadastro de clientes') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/clientes/edit.blade.php
@extends('layouts.app', ['page' => __('Gestão de Clientes'), 'pageSlug' => 'clientes'])

@section('content')
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">{{ __('Novo Cliente') }}</h5>
                </div>
                <form method="POST" action="{{ route('clientes.update',$cliente->id) }}" autocomplete="off">
                    <div class="card-body">
                            @csrf
                            @method('PUT')

                            <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                <label>{{ __('Nome') }}</label>
                                <input type="text" name="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Nome') }}" value="{{ $cliente->name }}">
                                @include('alerts.feedback', ['field' => 'name'])
                            </div>

                            <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                <label>{{ __('Email') }}</label>
                                <input type="text" name="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" placeholder="{{ __('E-mail') }}" value="{{ $cliente->email }}">
                                @include('alerts.feedback', ['field' => 'email'])
                            </div>

                            <div class="form-group{{ $errors->has('telefone') ? ' has-danger' : '' }}">
                                <label>{{ __('Telefone') }}</label>
                                <input type="text" id="telefone" name="telefone" class="form-control{{ $errors->has('telefone') ? ' is-invalid' : '' }}" placeholder="{{ __('Telefone') }}" value="{{ $cliente->telefone }}">
                                @include('alerts.feedback', ['field' => 'telefone'])
                            </div>

                            <div class="form-group{{ $errors->has('cpf') ? ' has-danger' : '' }}">
                                <label>{{ __('Cpf') }}</label>
                                <input type="text" id="cpf" name="cpf" class="form-control{{ $errors->has('cpf') ? ' is-invalid' : '' }}" placeholder="{{ __('cpf') }}" value="{{ $cliente->cpf }}">
                                @include('alerts.feedback', ['field' => 'cpf'])
                            </div>

                            <div class="form-group{{ $errors->has('indicacao') ? ' has-danger' : '' }}">
                                <label>{{ __('Indicação') }}</label>
                                <input type="text" name="indicacao" class="form-control{{ $errors->has('indicacao') ? ' is-invalid' : '' }}" placeholder="{{ __('indicacao') }}" value="{{ $cliente->indicacao }}">
                                @include('alerts.feedback', ['field' => 'indicacao'])
                            </div>

                            <div class="form-group{{ $errors->has('status') ? ' has-danger' : '' }}">
                                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                                  <label class="btn btn-light {{ $status['a'] }}">
                                    <input type="radio" name="status" id="ativo" value="A" checked> Ativo
                                  </label>
                                  <label class="btn btn-light {{ $status['d'] }}">
                                    <input type="radio" name="status" id="desativado" value="D"> Desativado
                                  </label>
                                </div>
                            </div>
                    </div>
                    <div class="card-footer">
                        <input type="hidden" name="id" value="{{ $cliente->id }}">
                        <button type="submit" class="btn btn-fill btn-primary">{{ __('Atualizar') }}</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card card-user">
                <div class="card-body">
                    <p class="card-text">
                        <div class="author">
                            <div class="block block-one"></div>
                            <div class="block block-two"></div>
                            <div class="block block-three"></div>
                            <div class="block block-four"></div>
                            <a href="#">
                                <h4 class="title">Bem vindo a edição de clientes</h4>
                                <h5 class="title">{{ auth()->user()->name }}</h5>
                            </a>
                            <p class="description">
                                {{ __('Teste') }}
                            </p>
                        </div>
                    </p>
                    <div class="card-description">
                        {{ __('Tela destinada ao cadastro de clientes') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/clientes/index.blade.php
@extends('layouts.app', ['page' => __('Lista de Clientes'), 'pageSlug' => 'clientes'])

@section('content')
<div class="content">
   <div class="row">
      <div class="col-md-12">
         <div class="card ">
            <div class="card-header">
               <div class="row">
                  <div class="col-8">
                     <h4 class="card-title">Clientes</h4>
                  </div>
                  <div class="col-4 text-right">
                     <a href="{{ route('clientes.create') }}" title="Novo Cliente" class="btn btn-sm btn-dark">
                     <i class="tim-icons icon-single-02"></i>
                     </a>
                  </div>
               </div>
            </div>
            <div class="card-body">
               @if ($message = Session::get('success'))
               <div class="alert alert-success">
                  <p>{{ $message }}</p>
               </div>
               @endif
            </div>
            <div class="card-body">
               <div class="table-responsive">
                  <table class="table tablesorter">
                     <thead class=" text-primary">
                        <tr>
                           <th scope="col">Nome</th>
                           <th scope="col">Telefone</th>
                           <th scope="col">CPF</th>
                           <th scope="col">Indicação</th>
                           <th scope="col">Status</th>
                           <th scope="col">Data de Criação</th>
                           <th scope="col"></th>
                        </tr>
                     </thead>
                     <tbody>
                        @foreach ($clientes as $cliente)
                        <tr>
                           <td>{{ $cliente->name }}</td>
                           <td>{{ $cliente->telefone }}</td>
                           <td>{{ $cliente->cpf }}</td>
                           <td>{{ $cliente->indicacao }}</td>
                           <td>
                              @if ($cliente->status =='A')
                              {{ __('Ativo') }}
                              @else
                              {{ __('Desativado') }}
                              @endif
                           </td>
                           <td>{{ $cliente->created_at->format('d/m/Y') }}</td>
                           <td class="text-right">
                              <div class="dropdown">
                                 <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                 <i class="fas fa-ellipsis-v"></i>
                                 </a>
                                 <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                    <a class="dropdown-item" href="{{ route('clientes.edit',$cliente->id) }}">Editar</a>
                                    <form action="{{ route('clientes.destroy',$cliente->id) }}" method="POST">
                                       @csrf
                                       @method('DELETE')
                                       <button type="submit" class="dropdown-item">Excluir</button>
                                    </form>
                                 </div>
                              </div>
                           </td>
                        </tr>
                        @endforeach
                     </tbody>
                  </table>
                  <div>
                    {{ $clientes->links() }}
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
@endsection