routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Auth::routes(['reset' => false, 'register' => false]);


Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::get('/graficos/graficos-total-emprestimos-mensal', 'GraficosController@graficosEmprestimosTotalMensal')->middleware('auth');
Route::get('/graficos/graficos-total-pagamento-mensais', 'GraficosController@graficosTotalPagamentoMensal')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

	Route::get('config', ['as' => 'config.edit', 'uses' => 'ConfiguracaoController@edit']);
	Route::put('config', ['as' => 'config.update', 'uses' => 'ConfiguracaoController@update']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('clientes', 'ClientesController', ['except' => ['show']]);
});


Route::group(['middleware' => 'auth'], function () {
	Route::resource('fluxoSaida', 'FluxoSaidaController');
	Route::get('gerar-pdf-emp/{id}', ['as' => 'fluxoSaida.pdf', 'uses' => 'FluxoSaidaController@gerarPdf']);
	Route::post('pagar', ['as' => 'fluxoSaida.pagamento', 'uses' => 'FluxoSaidaController@pagamento']);
	Route::post('pagar-total', ['as' => 'fluxoSaida.pagamento.total', 'uses' => 'FluxoSaidaController@pagamentoTotal']);
});

resources/views/layouts/navbars/navbar.blade.php
@auth()
    @include('layouts.navbars.navs.auth')
@endauth

@guest()
    @include('layouts.navbars.navs.guest')
@endguest

resources/views/layouts/navbars/sidebar.blade.php
<div class="sidebar">
    <div class="sidebar-wrapper">
        <div class="logo">
            <a href="#" class="simple-text logo-mini">{{ __('WL') }}</a>
            <a href="#" class="simple-text logo-normal">{{ __('Gestão') }}</a>
        </div>
        <ul class="nav">
            <li class="{{ $pageSlug == 'dashboard' ? ' active' : '' }}">
                <a href="{{ route('home') }}">
                    <i class="tim-icons icon-tap-02"></i>
                    <p>{{ __('Home') }}</p>
                </a>
            </li>
<!--             <li>
                <a data-toggle="collapse" href="#laravel-examples" aria-expanded="true">
                    <i class="fab fa-laravel" ></i>
                    <span class="nav-link-text" >{{ __('Usuários') }}</span>
                    <b class="caret mt-1"></b>
                </a>

                <div class="collapse show" id="laravel-examples">
                    <ul class="nav pl-4">
                        <li @if ($pageSlug ?? '' == 'profile') class="active " @endif>
                            <a href="{{ route('profile.edit')  }}">
                                <i class="tim-icons icon-single-02"></i>
                                <p>{{ __('Perfil do Usuário') }}</p>
                            </a>
                        </li>
                        <li @if ($pageSlug ?? '' == 'users') class="active " @endif>
                            <a href="{{ route('user.index')  }}">
                                <i class="tim-icons icon-bullet-list-67"></i>
                                <p>{{ __('Lista de Usuários') }}</p>
                            </a>
                        </li>
                    </ul>
                </div>
            </li> -->

            <li class="{{ $pageSlug == 'clientes' ? ' active' : '' }}">
                <a href="{{ route('clientes.index')  }}">
                  <i class="tim-icons icon-single-02" ></i>
                    <p>{{ __('Clientes') }}</p>
                </a>
            </li>
            <li class="{{ $pageSlug == 'emprestimos' ? ' active' : '' }}">
                <a href="{{ route('fluxoSaida.index')  }}">
                    <i class="tim-icons icon-bank"></i>
                    <p>{{ __('Emprestimos') }}</p>
                </a>
            </li>
            <li class="{{ $pageSlug == 'config' ? ' active' : '' }}">
                <a href="{{ route('config.edit')  }}">
                    <i class="tim-icons icon-settings"></i>
                    <p>{{ __('Configurações') }}</p>
                </a>
            </li>
        </ul>
    </div>
</div>