routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
*/

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index')->name('home');
Auth::routes(['reset' => false, 'register' => false]);


Route::get('/home', 'HomeController@index')->name('home')->middleware('auth');

Route::get('/graficos/graficos-total-emprestimos-mensal', 'GraficosController@graficosEmprestimosTotalMensal')->middleware('auth');
Route::get('/graficos/graficos-total-pagamento-mensais', 'GraficosController@graficosTotalPagamentoMensal')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);

	Route::get('config', ['as' => 'config.edit', 'uses' => 'ConfiguracaoController@edit']);
	Route::put('config', ['as' => 'config.update', 'uses' => 'ConfiguracaoController@update']);
});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('clientes', 'ClientesController', ['except' => ['show']]);
});


Route::group(['middleware' => 'auth'], function () {
	Route::resource('fluxoSaida', 'FluxoSaidaController');
	Route::get('gerar-pdf-emp/{id}', ['as' => 'fluxoSaida.pdf', 'uses' => 'FluxoSaidaController@gerarPdf']);
	Route::post('pagar', ['as' => 'fluxoSaida.pagamento', 'uses' => 'FluxoSaidaController@pagamento']);
	Route::post('pagar-total', ['as' => 'fluxoSaida.pagamento.total', 'uses' => 'FluxoSaidaController@pagamentoTotal']);
});

app/FluxoSaida.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use DB;

class FluxoSaida extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    protected $fillable = [
         'id_cliente', 'valor', 'parcelas', 'juros','valor_parcela', 'valor_total', 'status',
    ];

    protected $dates = ['vencimento', 'created_at'];


    public function clientes()
    {
        return $this->belongsTo('App\Clientes','id_cliente','id');
    }

    public function controlePagamentos()
    {
        return $this->hasMany('App\ControlePagamentos','id_fluxo_saidas','id');
    }

}

app/Http/Controllers/FluxoSaidaController.php
<?php

namespace App\Http\Controllers;

use App\FluxoSaida;
use App\Clientes;
use App\ControlePagamentos;
use Carbon\Carbon;
use App\Http\Requests\FluxoSaidaRequest;
use DB;

class FluxoSaidaController extends Controller
{
    public function index()
    {
        $emprestimos = FluxoSaida::with('clientes.fluxoSaida','controlePagamentos.fluxoSaida')
          ->where('status','A')
          ->orderBy('created_at','desc')
          ->paginate(6);

        return view('fluxoSaida.index',['emprestimos' => $emprestimos]);
    }

    /**
     * Novo emprestimo
     *
     * @return \Illuminate\View\View
     */

    public function create()
    {
        $clientes = Clientes::orderBy('created_at', 'desc')->get();
        return view('fluxoSaida.create', ['clientes' => $clientes]);
    }

    /**
     * Formata Valores
     *
     * @param $valor
     * @return $valorFormat
     */
    public function formatarValores($valor)
    {
      $source = array('.', ',');
      $replace = array('', '.');
      $valorFormat = str_replace($source, $replace, $valor);

      return $valorFormat;
    }

    /**
     * Calcular juros
     *
     * @param $valor, $parcelas, $juros
     * @return $valores
     */

    public function calculaJuros($valor, $parcelas, $juros)
    {
        $valorParcela = $valor / $parcelas;
        $calculo = $juros * $valor;
        $valorPercentualParcela = $calculo / 100;
        $totalParcela = $valorParcela + $valorPercentualParcela;
        $totalParcela = number_format($totalParcela,2,'.','');
        $totalPagar = $totalParcela * $parcelas;
        $valores = ['totalPagar' => $totalPagar, 'totalParcela' => $totalParcela];

        return $valores;
    }

    /**
     * Salvar Emprestimo
     *
     * @param  \App\Http\Requests\FluxoSaidaRequest  $request
     * @return \Illuminate\Http\RedirectResponse
     */

    public function store(FluxoSaidaRequest $request)
    {

        // $request->validate([
        //   'cliente' => 'required',
        //   'valor' => 'required',
        //   'parcelas' => 'required',
        //   'juros' => 'required',
        //   'vencimento' => 'required',
        // ]);

        $valorPagar = $this->formatarValores($request->valor);
        $valores = $this->calculaJuros($valorPagar, $request->parcelas, $request->juros);
        $vencimento = Carbon::createFromFormat('d/m/Y', $request->vencimento);

        $emprestimo = new FluxoSaida;
        $emprestimo->id_cliente         = $request->cliente;
        $emprestimo->valor              = $valorPagar;
        $emprestimo->parcelas           = $request->parcelas;
        $emprestimo->vencimento         = $vencimento;
        $emprestimo->juros              = $request->juros;
        $emprestimo->valor_parcela      = $valores['totalParcela'];
        $emprestimo->valor_total        = $valores['totalPagar'];
        $emprestimo->status             = 'A';
        $emprestimo->save();

        //$storagePath = public_path().'/promissorias/';
        // if (!file_exists($storagePath)) {
        //   mkdir($storagePath, 0777, true);
        // }

        for ($i=0; $i < $emprestimo->parcelas ; $i++) {
            $dtEmprestimo[] = Carbon::parse($emprestimo->vencimento)->addMonths($i);
            $dtName[] = Carbon::parse($dtEmprestimo[$i])->format('Y-m-d');
            $nomePromissoria[] = $dtName[$i].'-'.$emprestimo->id.'.pdf';

            $controlePag = new ControlePagamentos;
            $controlePag->id_fluxo_saidas = $emprestimo->id;
            $controlePag->vencimento      = $dtEmprestimo[$i];
            $controlePag->situacao        = 'pendente';
            $controlePag->vlr_pago        = '0.00';
            $controlePag->vlr_saldo       = '0.00';
            $controlePag->promissoria     = $nomePromissoria[$i];
            $controlePag->parcela         = $i+1;
            $controlePag->status          = 'A';
            $controlePag->save();

            $emprestimoProm = FluxoSaida::with('clientes.fluxoSaida','controlePagamentos.fluxoSaida')
              ->where('id',$controlePag->id_fluxo_saidas)
              ->first();

             \PDF::loadView('fluxoSaida.promissoria.modelo', compact('emprestimoProm'))
                      ->save($nomePromissoria[$i]);
        }

        return redirect()->route('fluxoSaida.index')
               ->with('success','Emprestimo cadastrado com sucesso.');
    }

    /**
     * Vizualizar Emprestimo
     *
     * @param $id
     * @return $emprestimo, $controle_pagamentos
     */

    public function show($id)
    {
        $emprestimo = FluxoSaida::with('clientes.fluxoSaida','controlePagamentos.fluxoSaida')
          ->where('id',$id)
          ->first();

        return view('fluxoSaida.show', compact('emprestimo'));
    }

    /**
     * GERAR PDF
     *
     * @param $id
     * @return $emprestimo
     */

    public function gerarPdf($id)
    {

        $emprestimo = FluxoSaida::with('clientes.fluxoSaida','controlePagamentos.fluxoSaida')
          ->where('id',$id)
          ->first();

        return \PDF::loadView('fluxoSaida.pdf_modelo.modelo', compact('emprestimo'))
                   ->stream();

    }

    /**
     * Controle de Pagamentos
     *
     * @param $request
     * @return
     */

    public function pagamento(FluxoSaidaRequest $request)
    {

      $pagParcela = ControlePagamentos::with('fluxoSaida.controlePagamentos')
        ->where('id',$request->id_pagamento)
        ->first();

      $pagamento = ControlePagamentos::findOrFail($request->id_pagamento);
      $valorPagar = $this->formatarValores($request->vlr_pago);

      if($valorPagar == $pagParcela->fluxoSaida->valor_parcela){
        $pagamento->vlr_pago = $valorPagar;
        $pagamento->situacao = "pago";
        $pagamento->update();
      }else{
        $valorPago = $pagParcela->vlr_pago + $valorPagar;
        $vlr_saldo = $pagParcela->fluxoSaida->valor_parcela - $valorPago;

        $pagamento->vlr_pago = $valorPago;
        if($vlr_saldo <= 0){
            $pagamento->situacao = "pago";
        }else{
            $pagamento->situacao = "pendente";
        }

        $pagamento->vlr_saldo = $vlr_saldo;
        $pagamento->update();
      }

      return back();
    }

    /**
     * Pagamento total da parcela
     *
     * @param $request
     * @return
     */

    public function pagamentoTotal(FluxoSaidaRequest $request)
    {

      $pagParcela = ControlePagamentos::with('fluxoSaida.controlePagamentos')
        ->where('id',$request->id)
        ->first();

      $pagamento = ControlePagamentos::findOrFail($request->id);
      $pagamento->vlr_pago = $pagParcela->fluxoSaida->valor_parcela;
      if($request->saldo){
        $pagamento->vlr_saldo = '0.00';
      }
      $pagamento->situacao  = 'pago';
      $pagamento->update();

      return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\FluxoSaida  $fluxoSaida
     * @return \Illuminate\Http\RedirectResponse
     */

    public function destroy(FluxoSaida $fluxoSaida)
    {
        $fluxoSaida->delete();

        return redirect()->route('fluxoSaida.index')
                        ->with('success','Emprestimo deletado com sucesso');
    }
}

resources/views/fluxoSaida/create.blade.php
@extends('layouts.app', ['page' => __('Novo Emprestimo'), 'pageSlug' => 'emprestimos'])

@section('content')
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">{{ __('Novo Emprestimo') }}</h5>
                </div>
                <form method="post" action="{{ route('fluxoSaida.store') }}" autocomplete="off">
                    <div class="card-body">
                            @csrf
                            @method('post')

                            <div class="form-group{{ $errors->has('cliente') ? ' has-danger' : '' }}">
                                <label>{{ __('Cliente') }}</label>
                                <select style="background-color: #2b3553" name="cliente" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="cliente">
                                  <option value="0">Selecione o Cliente</option>
                                  @foreach($clientes as $cli)
                                        <option value="{{ $cli->id }}">{{ $cli->name }}</option>
                                   @endforeach
                                </select>
                                @include('alerts.feedback', ['field' => 'cliente'])
                            </div>

                            <div class="form-group{{ $errors->has('valor') ? ' has-danger' : '' }}">
                                <label>{{ __('Valor do Emprestimo') }}</label>
                                <input type="text" id="valor" name="valor" class="form-control{{ $errors->has('valors') ? ' is-invalid' : '' }}" placeholder="{{ __('Valor do emprestimo') }}" value="">
                                @include('alerts.feedback', ['field' => 'valor'])
                            </div>

                            <div class="form-group{{ $errors->has('parcelas') ? ' has-danger' : '' }}">
                                <label>{{ __('Parcelas') }}</label>
                                <input type="text" name="parcelas" class="form-control{{ $errors->has('parcelas') ? ' is-invalid' : '' }}" placeholder="{{ __('Quantidades de Parcelas') }}" value="">
                                @include('alerts.feedback', ['field' => 'parcelas'])
                            </div>

                            <div class="form-group{{ $errors->has('vencimento') ? ' has-danger' : '' }}">
                                <label>{{ __('Data da 1º Parcela') }}</label>
                                <input type="text" id="dt_vencimento" name="vencimento" class="form-control{{ $errors->has('vencimento') ? ' is-invalid' : '' }}" placeholder="{{ __('Data da 1º Parcela') }}" value="">
                                @include('alerts.feedback', ['field' => 'vencimento'])
                            </div>

                            <div class="form-group{{ $errors->has('vencimento') ? ' has-danger' : '' }}">
                                <label>{{ __('Juros') }}</label>
                                <input type="text" name="juros" class="form-control{{ $errors->has('juros') ? ' is-invalid' : '' }}" placeholder="{{ __('Juros') }}" value="">
                                @include('alerts.feedback', ['field' => 'juros'])
                            </div>

                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-fill btn-primary">{{ __('Salvar') }}</button>
                    </div>
                </form>
            </div>
        </div>

        </div>
    </div>
@endsection

resources/views/fluxoSaida/edit.blade.php
@extends('layouts.app', ['page' => __('Gestão de Clientes'), 'pageSlug' => 'emprestimos'])

@section('content')
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h5 class="title">{{ __('Novo Cliente') }}</h5>
                </div>
                <form method="POST" action="{{ route('clientes.update',$cliente->id) }}" autocomplete="off">
                    <div class="card-body">
                            @csrf
                            @method('PUT')

                            <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                <label>{{ __('Nome') }}</label>
                                <input type="text" name="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Nome') }}" value="{{ $cliente->name }}">
                                @include('alerts.feedback', ['field' => 'name'])
                            </div>

                            <div class="form-group{{ $errors->has('email') ? ' has-danger' : '' }}">
                                <label>{{ __('Email') }}</label>
                                <input type="email" name="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}" placeholder="{{ __('E-mail') }}" value="{{ $cliente->email }}">
                                @include('alerts.feedback', ['field' => 'email'])
                            </div>

                            <div class="form-group{{ $errors->has('telefone') ? ' has-danger' : '' }}">
                                <label>{{ __('Telefone') }}</label>
                                <input type="telefone" id="telefone" name="telefone" class="form-control{{ $errors->has('telefone') ? ' is-invalid' : '' }}" placeholder="{{ __('Telefone') }}" value="{{ $cliente->telefone }}">
                                @include('alerts.feedback', ['field' => 'telefone'])
                            </div>

                            <div class="form-group{{ $errors->has('cpf') ? ' has-danger' : '' }}">
                                <label>{{ __('Cpf') }}</label>
                                <input type="cpf" id="cpf" name="cpf" class="form-control{{ $errors->has('cpf') ? ' is-invalid' : '' }}" placeholder="{{ __('cpf') }}" value="{{ $cliente->cpf }}">
                                @include('alerts.feedback', ['field' => 'cpf'])
                            </div>

                            <div class="form-group{{ $errors->has('indicacao') ? ' has-danger' : '' }}">
                                <label>{{ __('Indicação') }}</label>
                                <input type="cpf" name="indicacao" class="form-control{{ $errors->has('indicacao') ? ' is-invalid' : '' }}" placeholder="{{ __('indicacao') }}" value="{{ $cliente->indicacao }}">
                                @include('alerts.feedback', ['field' => 'indicacao'])
                            </div>

                            <div class="form-group{{ $errors->has('status') ? ' has-danger' : '' }}">
                                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                                  <label class="btn btn-light {{ $status['a'] }}">
                                    <input type="radio" name="status" id="ativo" value="A" checked> Ativo
                                  </label>
                                  <label class="btn btn-light {{ $status['d'] }}">
                                    <input type="radio" name="status" id="desativado" value="D"> Desativado
                                  </label>
                                </div>
                            </div>
                    </div>
                    <div class="card-footer">
                        <input type="hidden" name="id" value="{{ $cliente->id }}">
                        <button type="submit" class="btn btn-fill btn-primary">{{ __('Atualizar') }}</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card card-user">
                <div class="card-body">
                    <p class="card-text">
                        <div class="author">
                            <div class="block block-one"></div>
                            <div class="block block-two"></div>
                            <div class="block block-three"></div>
                            <div class="block block-four"></div>
                            <a href="#">
                                <h4 class="title">Bem vindo a edição de clientes</h4>
                                <h5 class="title">{{ auth()->user()->name }}</h5>
                            </a>
                            <p class="description">
                                {{ __('Teste') }}
                            </p>
                        </div>
                    </p>
                    <div class="card-description">
                        {{ __('Tela destinada ao cadastro de clientes') }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/fluxoSaida/index.blade.php
@extends('layouts.app', ['page' => __('Emprestimos'), 'pageSlug' => 'emprestimos'])

@section('content')

@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

<div class="content">
   <div class="row">
      <div class="col-md-12">
         <div class="card ">
            <div class="card-header">
               <div class="row">
                  <div class="col-8">
                     <h4 class="card-title">Emprestimos</h4>
                  </div>
                  <div class="col-4 text-right">
                     <a href="{{ route('fluxoSaida.create') }}" title="Novo empréstimo" class="btn btn-sm btn-dark">
                     <i class="tim-icons icon-money-coins"></i>
                     </a>
                  </div>
               </div>
            </div>
            <div class="card-body">
              @if ($message = Session::get('success'))
              <div class="alert alert-success">
                  <p>{{ $message }}</p>
              </div>
              @endif
            </div>
            <div class="card-body">
               <div class="table-responsive">
                  <table class="table tablesorter" id="">
                     <thead class=" text-primary">
                        <tr>
                           <th scope="col">Cliente</th>
                           <th scope="col">Valor</th>
                           <th scope="col">Parcelas</th>
                           <th scope="col">1° Venc</th>
                           <th scope="col">Juros</th>
                           <th scope="col">Total</th>
                           <th scope="col">Solicitaçao</th>
                           <th scope="col">Status</th>
                           <th scope="col"></th>
                        </tr>
                     </thead>
                     <tbody>
                        @foreach ($emprestimos as $emp)
                        <tr>
                           <td>{{ $emp->clientes->name }}</td>
                           <td>
                              <span style="color:red">
                              R$ {{ number_format($emp->valor,2) }}
                              </span>
                           </td>
                           <td>{{ $emp->parcelas }} / R$ {{ $emp->valor_parcela }}</td>
                           <td>
                              <span style="color:teal">
                              {{ $emp->vencimento->format('d/m/Y') }}
                              </span>
                           </td>
                           <td class="text-center">{{ $emp->juros }}%</td>
                           <td>
                              <span style="color:yellow">
                              R$ {{ $emp->valor_total }}
                              </span>
                           </td>
                           <td>{{ $emp->created_at->format('d/m/Y') }}</td>
                           <td>
                              @if($emp->controlePagamentos->sum('vlr_pago') == $emp->valor_total)
                              Pago
                              @else
                              Pendente
                              @endif
                           </td>
                           <td class="text-right">
                              <div class="dropdown">
                                 <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                 <i class="fas fa-ellipsis-v"></i>
                                 </a>
                                 <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                    <a class="dropdown-item" href="{{ route('fluxoSaida.show',$emp->id) }}">Informações</a>
                                    <a class="dropdown-item" target="_blank" href="{{ route('fluxoSaida.pdf' ,$emp->id) }}">Gerar PDF</a>
                                    <!-- <a class="dropdown-item" href="{{ route('clientes.edit',$emp->id) }}">Editar</a> -->
                                    <form action="{{ route('fluxoSaida.destroy',$emp->id) }}" method="POST">
                                       @csrf
                                       @method('DELETE')
                                       <button type="submit" class="dropdown-item">Excluir</button>
                                    </form>
                                 </div>
                              </div>
                           </td>
                        </tr>
                        @endforeach
                     </tbody>
                  </table>
                  <div>
                    {{ $emprestimos->links() }}
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
@endsection

resources/views/fluxoSaida/show.blade.php
@extends('layouts.app', ['page' => __('Emprestimos'), 'pageSlug' => 'emprestimos'])

@section('content')

<div id="modalPag" class="modal">
    <form method="post" action="{{ route('fluxoSaida.pagamento') }}" autocomplete="off">
        <div class="card-body">
                @csrf
                @method('post')

                <div class="form-group">
                    <label>{{ __('Valor a Pagar') }}</label>
                    <input type="text" id="vlr_pagar" name="vlr_pago" class="form-control" style="color: #000 !important;" placeholder="{{ __('Valor a Pagar') }}" value="">
                    <input type="hidden" id="id_pagamento" name="id_pagamento">
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-fill btn-primary">{{ __('Pagar') }}</button>
                </div>
        </div>
    </form>
  <!-- <a href="#" rel="modal:close">Close</a> -->
</div>

<div class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="card ">
        <div class="card-header">
          <div class="row">
              <div class="col-8">
                  <h4 class="card-title">Visualizar Emprestimo</h4>
              </div>
              <div class="col-4 text-right">
                  <a href="{{ route('fluxoSaida.index') }}" class="btn btn-sm btn-primary">Voltar</a>
              </div>
          </div>
          <div class="card-body">
            <div class="table-responsive">
                <table class="table tablesorter " id="">
                    <thead class=" text-primary">
                        <tr>
                        <th scope="col">Cliente</th>
                        <th scope="col">Valor</th>
                        <th scope="col">Parcelas</th>
                        <th scope="col">Juros ao Mês</th>
                        <th scope="col">Dia Venc</th>
                        <th scope="col">Total a pagar</th>
                        <th scope="col">Solicitaçao</th>
                    </tr>
                  </thead>
                    <tbody>
                      <tr>
                        <td>{{ $emprestimo->clientes->name }}</td>
                        <td>R$ {{ $emprestimo->valor }}</td>
                        <td>{{ $emprestimo->parcelas }}</td>
                        <td>{{ $emprestimo->juros }}%</td>
                        <td>{{ $emprestimo->vencimento->format('d') }}</td>
                        <td>R$ {{ $emprestimo->valor_total }}</td>
                        <td>{{ $emprestimo->created_at->format('d/m/Y') }}</td>
                        <td>
                          <span><i class="fa fa-whatsapp" style="font-size:25px" title="Enviar Whats"></i></span>
                          <span><i class="fa fa-envelope" style="font-size:25px" title="Enviar Email"></i></span>
                        </td>
                      </tr>
                  </tbody>
                </table>
            </div>
          </div>

          <div class="card-body">
            <div class="table-responsive">
            <table class="table tablesorter">
                <thead class=" text-primary" data-id="{{ $emprestimo->id }}">
                    <tr>
                    <th scope="col">Parc</th>
                    <th scope="col">Datas</th>
                    <th scope="col">Valor</th>
                    <th scope="col">Pago</th>
                    <th scope="col">Saldo</th>
                    <th scope="col">Situaçao</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
              </thead>
                <tbody>
                  @foreach($emprestimo->controlePagamentos as $key => $contr)
                  <tr>
                    <td>{{ $key+1 }}</td>
                    <td>{{ $contr->vencimento->format('d/m/Y') }}</td>
                    <td>R$ {{ $emprestimo->valor_parcela }}</td>
                    <td>R$ {{ $contr->vlr_pago }}</td>
                    <td>R$ {{ $contr->vlr_saldo }}</td>
                    <td>{{ strtoupper($contr->situacao) }}</td>
                    <td>
                      <a href="..\{{ $contr->promissoria }}" target="_blank">
                        <i title="Gerar Promissória" class="fa fa-file-pdf-o" aria-hidden="true" style="font-size: 25px"></i>
                      </a>
                    </td>
                    <td class="text-center">
                      @if($contr->vlr_saldo > '0.01' || $contr->vlr_pago == '0.00')
                        <form method="post" action="{{ route('fluxoSaida.pagamento.total') }}" autocomplete="off">
                          @csrf
                          @method('post')

                         <input type="hidden" name="id" value="{{$contr->id}}">
                         <input type="hidden" name="saldo" value="{{$contr->vlr_saldo}}">
                         <button type="submit" class="btn btn-sm btn-icon-only text-light">Quitar</button>
                      </form>
                      @endif
                    </td>
                    <td>
                      @if($contr->vlr_saldo > '0.01' || $contr->vlr_pago == '0.00')
                      <a class="btn btn-sm btn-icon-only text-light pagamento" href="#modalPag"  rel="modal:open" role="button" data-id="{{ $contr->id }}">
                        Parcelar
                      </a>
                      @endif
                    </td>
                  </tr>
                  @endforeach
              </tbody>
            </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection